### PR TITLE
start howToShavarList doc

### PR DESCRIPTION
**Pull request by groovecoder**

### CODE REVIEW

**Comment by rbillings** [comment]
Suggested first draft:
### QA
If you need server side testing, contact Firefox Test Engineering. If you need client side testing, contact SoftVision. Many times both will be required.

Server side testing will require new lists to be added to Staging. 
Testing new lists will require providing a set of testing prefs and an update to the [prefs .ini file.](https://github.com/mozilla-services/services-test/blob/master/shavar/e2e-test/prefs.ini)

**Comment by groovecoder** [comment]
@rbillings - what link should I use for "Firefox Test Engineering" ?

**Comment by groovecoder** [comment]
@rbillings I updated this PR to include a QA section. Can you look it over to see that it captures & matches your comment?

**Comment by rbillings** [comment]
The QA section works. If you did want to add a link [my bad for neglecting it!], it would be:  https://readthedocs.org/projects/firefox-test-engineering/

**Pull request merged**
